### PR TITLE
[MAINT, MRG] Fixes for francois

### PR DESCRIPTION
**Pull request by alexrockhill**
Thanks for all your help @effigies and @nellh! I think this is all the changes I wanted and I can just merge this and I'll have my dataset updated!

### CODE REVIEW

**Comment by alexrockhill** [comment]
Major file reorganizations are very hard to view on the GitHub diff but I think I've done it right...

Maybe this should be a PR to `OpenNeuroDatasets:git-annex`? Not sure

**Comment by alexrockhill** [comment]
Ok to merge?

**Comment by effigies** [comment]
Sorry, we will not be able to merge from here. These datasets must remain mirrors of the latest snapshot on OpenNeuro, or we risk losing dataset consistency. If you're having issues pushing to the OpenNeuro git interface, that will need to be handled.

That said, this can stay open for inspection.

Apologies for the delayed responses. We're currently having a significant sprint on a different tool. We expect to get back to normal levels of OpenNeuro support next week.

**Comment by alexrockhill** [comment]
I only did a PR because the git interface doesn't allow you to delete or move files. All I want to do is upload an exact version of my local directory as a new draft that I can make a snapshot of, how do I do that?

**Comment by alexrockhill** [comment]
I read the instructions carefully about making a new dataset and redirecting the old one so I'll just go ahead and do that.

**Comment by nellh** [comment]
> I only did a PR because the git interface doesn't allow you to delete or move files. All I want to do is upload an exact version of my local directory as a new draft that I can make a snapshot of, how do I do that?

The git interface does allow you to do this. Please open an OpenNeuro issue if you are having problems with it, I saw the stream closure warning you reported and should have a fix for that sometime next week.

**Comment by alexrockhill** [comment]
All I see is the documentation here: https://docs.openneuro.org/git. It doesn't describe how to push changes, it only mentions that you can. I made a PR here since I thought that was the mechanism. Is there some documentation on how to do this?

**Comment by nellh** [comment]
If you follow the [instructions for cloning from OpenNeuro](https://docs.openneuro.org/git#usage), you can use git mv, git rm, git add to modify the local copy and then push that back to OpenNeuro. There's some [additional steps documented](https://docs.openneuro.org/git#git-annex-special-remote) for pushing annexed objects if you have data file changes (other than just moving/renaming).

You can also start with a GitHub clone, but you'll want to add OpenNeuro as a new remote and pull from it before making changes. The draft can be ahead of what's on GitHub, since only snapshots are pushed here.

**Pull request closed without merging**
